version: 0.2
phases:
  install:
    commands:
      - "apt-get install unzip -y" # install unzip
      - "wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip"
      - "unzip terraform_0.12.18_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
       
  pre_build:
    commands:
      - AWS_ACCESS_KEY_ID=AKIAR2EZRNJ2EDKZKKPZ
      - AWS_SECRET_ACCESS_KEY=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
      - terraform --version
      - terraform init
      - terraform validate
  build:
    commands:
      - ASSUME_ROLE_ARN="arn:aws:iam::124876057204:role/ssm-parameter-store"


      - terraform apply -auto-approve
  post_build:
    commands:
      - echo terraform apply completed on 'date'
    
